version: '3'

services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=editora
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/editora
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres: