default: &default
  adapter: postgresql
  database: "<%= ENV.fetch('POSTGRES_DATABASE', 'editora') %>"
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 25) %> 

development:
  <<: *default
  database: "<%= ENV.fetch('POSTGRES_DATABASE', 'editora') %>"
  username: postgres
  password: postgres
test:
  <<: *default
  database: "<%= ENV.fetch('POSTGRES_DATABASE', 'editora') %>"
  username: postgres
  password: postgres

production:
  <<: *default
  database: "<%= ENV.fetch('POSTGRES_DATABASE', 'editora') %>"
  username: postgres
  password: postgres
